/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */

import javax.swing.JOptionPane;
public class FRM_Fragmentado extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Fragmentado
     */
    public FRM_Fragmentado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_alternativasFrag = new javax.swing.ButtonGroup();
        btn_avancarFrag = new javax.swing.JButton();
        btn_desenvolFrag = new javax.swing.JButton();
        btn_voltarFrag = new javax.swing.JButton();
        btn_sairFrag = new javax.swing.JButton();
        btn_limparFrag = new javax.swing.JButton();
        rdb_Frag1 = new javax.swing.JRadioButton();
        rdb_Frag2 = new javax.swing.JRadioButton();
        rdb_Frag3 = new javax.swing.JRadioButton();
        rdb_Frag4 = new javax.swing.JRadioButton();
        lbl_imgFrag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adivinhando Fragmentado");
        setMinimumSize(new java.awt.Dimension(650, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        btn_avancarFrag.setBackground(new java.awt.Color(0, 0, 0));
        btn_avancarFrag.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_avancarFrag.setForeground(new java.awt.Color(255, 255, 255));
        btn_avancarFrag.setText("Avançar");
        btn_avancarFrag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_avancarFragActionPerformed(evt);
            }
        });
        getContentPane().add(btn_avancarFrag);
        btn_avancarFrag.setBounds(550, 570, 77, 30);

        btn_desenvolFrag.setBackground(new java.awt.Color(0, 0, 0));
        btn_desenvolFrag.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_desenvolFrag.setForeground(new java.awt.Color(255, 255, 255));
        btn_desenvolFrag.setText("Desenvolvedor");
        btn_desenvolFrag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desenvolFragActionPerformed(evt);
            }
        });
        getContentPane().add(btn_desenvolFrag);
        btn_desenvolFrag.setBounds(220, 570, 120, 30);

        btn_voltarFrag.setBackground(new java.awt.Color(0, 0, 0));
        btn_voltarFrag.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_voltarFrag.setForeground(new java.awt.Color(255, 255, 255));
        btn_voltarFrag.setText("Voltar");
        btn_voltarFrag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarFragActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltarFrag);
        btn_voltarFrag.setBounds(20, 570, 70, 30);

        btn_sairFrag.setBackground(new java.awt.Color(0, 0, 0));
        btn_sairFrag.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sairFrag.setForeground(new java.awt.Color(255, 255, 255));
        btn_sairFrag.setText("Sair");
        btn_sairFrag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairFragActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sairFrag);
        btn_sairFrag.setBounds(120, 570, 75, 30);

        btn_limparFrag.setBackground(new java.awt.Color(0, 0, 0));
        btn_limparFrag.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_limparFrag.setForeground(new java.awt.Color(255, 255, 255));
        btn_limparFrag.setText("Limpar");
        btn_limparFrag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparFragActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limparFrag);
        btn_limparFrag.setBounds(20, 380, 75, 30);

        grp_alternativasFrag.add(rdb_Frag1);
        rdb_Frag1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Frag1.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Frag1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Frag1ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Frag1);
        rdb_Frag1.setBounds(20, 160, 340, 40);

        grp_alternativasFrag.add(rdb_Frag2);
        rdb_Frag2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Frag2.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Frag2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Frag2ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Frag2);
        rdb_Frag2.setBounds(20, 210, 360, 40);

        grp_alternativasFrag.add(rdb_Frag3);
        rdb_Frag3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Frag3.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Frag3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Frag3ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Frag3);
        rdb_Frag3.setBounds(20, 260, 380, 40);

        grp_alternativasFrag.add(rdb_Frag4);
        rdb_Frag4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Frag4.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Frag4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Frag4ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Frag4);
        rdb_Frag4.setBounds(20, 310, 380, 40);

        lbl_imgFrag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgfrag.png"))); // NOI18N
        getContentPane().add(lbl_imgFrag);
        lbl_imgFrag.setBounds(0, 0, 650, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_avancarFragActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_avancarFragActionPerformed
        new FRM_BastardosInglorios( ).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_avancarFragActionPerformed

    private void btn_desenvolFragActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desenvolFragActionPerformed
            new FRM_Desenvol( ).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_desenvolFragActionPerformed

    private void btn_voltarFragActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarFragActionPerformed
        new FRM_ClubeDaLuta( ).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_voltarFragActionPerformed

    private void btn_sairFragActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairFragActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_sairFragActionPerformed

    private void btn_limparFragActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparFragActionPerformed
        grp_alternativasFrag.clearSelection();
    }//GEN-LAST:event_btn_limparFragActionPerformed

    private void rdb_Frag1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Frag1ActionPerformed
        if (rdb_Frag1.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\nKevin foi diagnosticado com Transtorno Dissociativo\nde Identidade (TDI), por isso, ele possui mais de\numa identidade.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Frag1.setSelected(false);}
    }//GEN-LAST:event_rdb_Frag1ActionPerformed

    private void rdb_Frag2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Frag2ActionPerformed
            if (rdb_Frag2.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\nKevin possui outras personalidades, mas 3 não é a quantidade exata.\n\nDica: Kevin possui mais de 10 personalidades.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Frag2.setSelected(false);}
    }//GEN-LAST:event_rdb_Frag2ActionPerformed

    private void rdb_Frag3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Frag3ActionPerformed
        if (rdb_Frag3.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\nKevin possui outras personalidades,\nmas 13 não é a quantidade exata.\n\nCada uma delas pode ter um nome,\nhistórico pessoal e característica distintos.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Frag3.setSelected(false);}
    }//GEN-LAST:event_rdb_Frag3ActionPerformed

    private void rdb_Frag4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Frag4ActionPerformed
        JOptionPane.showMessageDialog(null,"Parabéns, você acertou!\n\nO Kevin possui 23 personalidades distintas e\nconsegue alterná-las quimicamente em seu\norganismo apenas com a força do pensamento.","Alternativa Correta!",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rdb_Frag4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Fragmentado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Fragmentado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Fragmentado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Fragmentado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Fragmentado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_avancarFrag;
    private javax.swing.JButton btn_desenvolFrag;
    private javax.swing.JButton btn_limparFrag;
    private javax.swing.JButton btn_sairFrag;
    private javax.swing.JButton btn_voltarFrag;
    private javax.swing.ButtonGroup grp_alternativasFrag;
    private javax.swing.JLabel lbl_imgFrag;
    private javax.swing.JRadioButton rdb_Frag1;
    private javax.swing.JRadioButton rdb_Frag2;
    private javax.swing.JRadioButton rdb_Frag3;
    private javax.swing.JRadioButton rdb_Frag4;
    // End of variables declaration//GEN-END:variables
}
