/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class FRM_PrincipalMenu extends javax.swing.JFrame {

    /**
     * Creates new form FRM_PrincipalMenu
     */
    public FRM_PrincipalMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        tlb_menu = new javax.swing.JToolBar();
        btn_alice = new javax.swing.JButton();
        btn_clube = new javax.swing.JButton();
        btn_fragmentado = new javax.swing.JButton();
        btn_bastardos = new javax.swing.JButton();
        btn_interestelar = new javax.swing.JButton();
        btn_silencio = new javax.swing.JButton();
        btn_walle = new javax.swing.JButton();
        lbl_espaco = new javax.swing.JLabel();
        btn_agrade = new javax.swing.JButton();
        btn_dev = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        pnl_base = new javax.swing.JPanel();
        pnl_fundo = new javax.swing.JPanel();
        lbl_imgfundo = new javax.swing.JLabel();
        mnb_menubar = new javax.swing.JMenuBar();
        mnp_qts = new javax.swing.JMenu();
        mni_alice = new javax.swing.JMenuItem();
        mni_clube = new javax.swing.JMenuItem();
        mni_fragmentado = new javax.swing.JMenuItem();
        mni_bastardos = new javax.swing.JMenuItem();
        mni_interes = new javax.swing.JMenuItem();
        mni_silencio = new javax.swing.JMenuItem();
        mni_walle = new javax.swing.JMenuItem();
        mnp_agrade = new javax.swing.JMenu();
        mni_agrade = new javax.swing.JMenuItem();
        mnp_dev = new javax.swing.JMenu();
        mni_dev = new javax.swing.JMenuItem();
        mnp_sair = new javax.swing.JMenu();
        mni_sair = new javax.swing.JMenuItem();

        jButton8.setText("jButton8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(751, 852));
        setMinimumSize(new java.awt.Dimension(751, 852));
        setPreferredSize(new java.awt.Dimension(650, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(751, 852));
        getContentPane().setLayout(null);

        tlb_menu.setBackground(new java.awt.Color(0, 0, 0));
        tlb_menu.setRollover(true);
        tlb_menu.setBorderPainted(false);

        btn_alice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alice.png"))); // NOI18N
        btn_alice.setFocusable(false);
        btn_alice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_alice.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_alice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aliceActionPerformed(evt);
            }
        });
        tlb_menu.add(btn_alice);

        btn_clube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clubedaluta.png"))); // NOI18N
        btn_clube.setFocusable(false);
        btn_clube.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_clube.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_clube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clubeActionPerformed(evt);
            }
        });
        tlb_menu.add(btn_clube);

        btn_fragmentado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/split.png"))); // NOI18N
        btn_fragmentado.setFocusable(false);
        btn_fragmentado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_fragmentado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_fragmentado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fragmentadoActionPerformed(evt);
            }
        });
        tlb_menu.add(btn_fragmentado);

        btn_bastardos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soldier.png"))); // NOI18N
        btn_bastardos.setFocusable(false);
        btn_bastardos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_bastardos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_bastardos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bastardosActionPerformed(evt);
            }
        });
        tlb_menu.add(btn_bastardos);

        btn_interestelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interico.png"))); // NOI18N
        btn_interestelar.setFocusable(false);
        btn_interestelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_interestelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_interestelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_interestelarActionPerformed(evt);
            }
        });
        tlb_menu.add(btn_interestelar);

        btn_silencio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mariposa.png"))); // NOI18N
        btn_silencio.setFocusable(false);
        btn_silencio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_silencio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_silencio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silencioActionPerformed(evt);
            }
        });
        tlb_menu.add(btn_silencio);

        btn_walle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robot.png"))); // NOI18N
        btn_walle.setFocusable(false);
        btn_walle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_walle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_walle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_walleActionPerformed(evt);
            }
        });
        tlb_menu.add(btn_walle);

        lbl_espaco.setText("----");
        tlb_menu.add(lbl_espaco);

        btn_agrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thank-you.png"))); // NOI18N
        btn_agrade.setFocusable(false);
        btn_agrade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_agrade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_agrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agradeActionPerformed(evt);
            }
        });
        tlb_menu.add(btn_agrade);

        btn_dev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/girl.png"))); // NOI18N
        btn_dev.setFocusable(false);
        btn_dev.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dev.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_devActionPerformed(evt);
            }
        });
        tlb_menu.add(btn_dev);

        btn_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        btn_sair.setFocusable(false);
        btn_sair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_sair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });
        tlb_menu.add(btn_sair);

        getContentPane().add(tlb_menu);
        tlb_menu.setBounds(-10, 0, 760, 70);

        pnl_base.setEnabled(false);
        pnl_base.setOpaque(false);
        pnl_base.setLayout(null);
        getContentPane().add(pnl_base);
        pnl_base.setBounds(0, 70, 750, 760);

        pnl_fundo.setBackground(new java.awt.Color(0, 0, 0));
        pnl_fundo.setLayout(null);

        lbl_imgfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu.jpg"))); // NOI18N
        pnl_fundo.add(lbl_imgfundo);
        lbl_imgfundo.setBounds(0, 20, 750, 810);

        getContentPane().add(pnl_fundo);
        pnl_fundo.setBounds(0, 0, 760, 830);

        mnb_menubar.setBackground(new java.awt.Color(0, 0, 0));
        mnb_menubar.setBorderPainted(false);

        mnp_qts.setText("Questões");
        mnp_qts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnp_qtsActionPerformed(evt);
            }
        });

        mni_alice.setText("1ª - Alice no País das Maravilhas");
        mni_alice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_aliceActionPerformed(evt);
            }
        });
        mnp_qts.add(mni_alice);

        mni_clube.setText("2ª - Clube da Luta");
        mni_clube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_clubeActionPerformed(evt);
            }
        });
        mnp_qts.add(mni_clube);

        mni_fragmentado.setText("3ª - Fragmentado");
        mni_fragmentado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_fragmentadoActionPerformed(evt);
            }
        });
        mnp_qts.add(mni_fragmentado);

        mni_bastardos.setText("4ª - Bastardos Inglórios");
        mni_bastardos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_bastardosActionPerformed(evt);
            }
        });
        mnp_qts.add(mni_bastardos);

        mni_interes.setText("5ª - Interestelar");
        mni_interes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_interesActionPerformed(evt);
            }
        });
        mnp_qts.add(mni_interes);

        mni_silencio.setText("6ª - O Silêncio dos Inocentes");
        mni_silencio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_silencioActionPerformed(evt);
            }
        });
        mnp_qts.add(mni_silencio);

        mni_walle.setText("7ª - Wall-E");
        mni_walle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_walleActionPerformed(evt);
            }
        });
        mnp_qts.add(mni_walle);

        mnb_menubar.add(mnp_qts);

        mnp_agrade.setText("Agradecimento");
        mnp_agrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnp_agradeActionPerformed(evt);
            }
        });

        mni_agrade.setText("Agradecimento");
        mni_agrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_agradeActionPerformed(evt);
            }
        });
        mnp_agrade.add(mni_agrade);

        mnb_menubar.add(mnp_agrade);

        mnp_dev.setText("Desenvolvedor");
        mnp_dev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnp_devActionPerformed(evt);
            }
        });

        mni_dev.setText("Desenvolvedor");
        mni_dev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_devActionPerformed(evt);
            }
        });
        mnp_dev.add(mni_dev);

        mnb_menubar.add(mnp_dev);

        mnp_sair.setBackground(new java.awt.Color(255, 0, 0));
        mnp_sair.setText("Sair");
        mnp_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnp_sairActionPerformed(evt);
            }
        });

        mni_sair.setText("Sair");
        mni_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_sairActionPerformed(evt);
            }
        });
        mnp_sair.add(mni_sair);

        mnb_menubar.add(mnp_sair);

        setJMenuBar(mnb_menubar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mni_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mni_sairActionPerformed

    private void mnp_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnp_sairActionPerformed

    }//GEN-LAST:event_mnp_sairActionPerformed

    private void mni_devActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_devActionPerformed
       ifrm_desenvolvedor frm = new  ifrm_desenvolvedor();
        frm.setVisible(true);
        pnl_base.add( frm );
    }//GEN-LAST:event_mni_devActionPerformed

    private void mnp_devActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnp_devActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnp_devActionPerformed

    private void mni_aliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_aliceActionPerformed
        ifrm_alice frm = new  ifrm_alice();
        frm.setVisible(true);
        pnl_base.add( frm );
    }//GEN-LAST:event_mni_aliceActionPerformed

    private void btn_aliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aliceActionPerformed
        ifrm_alice frm = new  ifrm_alice();
        frm.setVisible(true);
        pnl_base.add( frm );
    }//GEN-LAST:event_btn_aliceActionPerformed

    private void btn_clubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clubeActionPerformed
        ifrm_clubedaluta frm = new  ifrm_clubedaluta();
        frm.setVisible(true);
        pnl_base.add( frm );
    }//GEN-LAST:event_btn_clubeActionPerformed

    private void mni_clubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_clubeActionPerformed
       ifrm_clubedaluta frm = new  ifrm_clubedaluta();
        frm.setVisible(true);
        pnl_base.add( frm );
    }//GEN-LAST:event_mni_clubeActionPerformed

    private void btn_fragmentadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fragmentadoActionPerformed
        ifrm_fragmentado frm = new  ifrm_fragmentado();
        frm.setVisible(true);
        pnl_base.add( frm );
    }//GEN-LAST:event_btn_fragmentadoActionPerformed

    private void mnp_qtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnp_qtsActionPerformed
       
    }//GEN-LAST:event_mnp_qtsActionPerformed

    private void btn_bastardosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bastardosActionPerformed
        ifrm_bastardos frm = new  ifrm_bastardos();
        frm.setVisible(true);
        pnl_base.add( frm );
    }//GEN-LAST:event_btn_bastardosActionPerformed

    private void mni_bastardosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_bastardosActionPerformed
        ifrm_bastardos frm = new  ifrm_bastardos();
        frm.setVisible(true);
        pnl_base.add( frm );
    }//GEN-LAST:event_mni_bastardosActionPerformed

    private void btn_interestelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_interestelarActionPerformed
        ifrm_interestelar frm = new  ifrm_interestelar();
        frm.setVisible(true);
        pnl_base.add( frm );
    }//GEN-LAST:event_btn_interestelarActionPerformed

    private void mni_interesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_interesActionPerformed
        ifrm_interestelar frm = new  ifrm_interestelar();
        frm.setVisible(true);
        pnl_base.add( frm );
    }//GEN-LAST:event_mni_interesActionPerformed

    private void btn_silencioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silencioActionPerformed
        ifrm_silenciodosinocentes frm = new  ifrm_silenciodosinocentes();
        frm.setVisible(true);
        pnl_base.add( frm );
    }//GEN-LAST:event_btn_silencioActionPerformed

    private void mni_silencioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_silencioActionPerformed
       ifrm_silenciodosinocentes frm = new  ifrm_silenciodosinocentes();
        frm.setVisible(true);
        pnl_base.add( frm );
    }//GEN-LAST:event_mni_silencioActionPerformed

    private void btn_walleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_walleActionPerformed
       ifrm_walle frm = new  ifrm_walle();
        frm.setVisible(true);
        pnl_base.add( frm );
    }//GEN-LAST:event_btn_walleActionPerformed

    private void mni_walleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_walleActionPerformed
       ifrm_walle frm = new  ifrm_walle();
        frm.setVisible(true);
        pnl_base.add( frm );
    }//GEN-LAST:event_mni_walleActionPerformed

    private void mni_fragmentadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_fragmentadoActionPerformed
        ifrm_fragmentado frm = new  ifrm_fragmentado();
        frm.setVisible(true);
        pnl_base.add( frm );
    }//GEN-LAST:event_mni_fragmentadoActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_agradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agradeActionPerformed
       ifrm_agradecimento frm = new  ifrm_agradecimento();
        frm.setVisible(true);
        pnl_base.add( frm );
    }//GEN-LAST:event_btn_agradeActionPerformed

    private void mnp_agradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnp_agradeActionPerformed
      
    }//GEN-LAST:event_mnp_agradeActionPerformed

    private void btn_devActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_devActionPerformed
       ifrm_desenvolvedor frm = new  ifrm_desenvolvedor();
        frm.setVisible(true);
        pnl_base.add( frm );
    }//GEN-LAST:event_btn_devActionPerformed

    private void mni_agradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_agradeActionPerformed
        ifrm_agradecimento frm = new  ifrm_agradecimento();
        frm.setVisible(true);
        pnl_base.add( frm );
    }//GEN-LAST:event_mni_agradeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_PrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_PrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_PrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_PrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_PrincipalMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agrade;
    private javax.swing.JButton btn_alice;
    private javax.swing.JButton btn_bastardos;
    private javax.swing.JButton btn_clube;
    private javax.swing.JButton btn_dev;
    private javax.swing.JButton btn_fragmentado;
    private javax.swing.JButton btn_interestelar;
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton btn_silencio;
    private javax.swing.JButton btn_walle;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel lbl_espaco;
    private javax.swing.JLabel lbl_imgfundo;
    private javax.swing.JMenuBar mnb_menubar;
    private javax.swing.JMenuItem mni_agrade;
    private javax.swing.JMenuItem mni_alice;
    private javax.swing.JMenuItem mni_bastardos;
    private javax.swing.JMenuItem mni_clube;
    private javax.swing.JMenuItem mni_dev;
    private javax.swing.JMenuItem mni_fragmentado;
    private javax.swing.JMenuItem mni_interes;
    private javax.swing.JMenuItem mni_sair;
    private javax.swing.JMenuItem mni_silencio;
    private javax.swing.JMenuItem mni_walle;
    private javax.swing.JMenu mnp_agrade;
    private javax.swing.JMenu mnp_dev;
    private javax.swing.JMenu mnp_qts;
    private javax.swing.JMenu mnp_sair;
    private javax.swing.JPanel pnl_base;
    private javax.swing.JPanel pnl_fundo;
    private javax.swing.JToolBar tlb_menu;
    // End of variables declaration//GEN-END:variables
}
