/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author chicl
 */
public class FRM_MenuFinal extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MenuFinal
     */
    public FRM_MenuFinal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_MenuFim = new javax.swing.JButton();
        btn_voltarFim = new javax.swing.JButton();
        btn_sairFim = new javax.swing.JButton();
        btn_desenvolFim = new javax.swing.JButton();
        lbl_imgFim = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Final");
        setMinimumSize(new java.awt.Dimension(650, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        btn_MenuFim.setBackground(new java.awt.Color(0, 0, 0));
        btn_MenuFim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_MenuFim.setForeground(new java.awt.Color(255, 255, 255));
        btn_MenuFim.setText("Menu Principal");
        btn_MenuFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuFimActionPerformed(evt);
            }
        });
        getContentPane().add(btn_MenuFim);
        btn_MenuFim.setBounds(507, 570, 120, 30);

        btn_voltarFim.setBackground(new java.awt.Color(0, 0, 0));
        btn_voltarFim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_voltarFim.setForeground(new java.awt.Color(255, 255, 255));
        btn_voltarFim.setText("Voltar");
        btn_voltarFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarFimActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltarFim);
        btn_voltarFim.setBounds(20, 570, 70, 30);

        btn_sairFim.setBackground(new java.awt.Color(0, 0, 0));
        btn_sairFim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sairFim.setForeground(new java.awt.Color(255, 255, 255));
        btn_sairFim.setText("Sair");
        btn_sairFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairFimActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sairFim);
        btn_sairFim.setBounds(120, 570, 75, 30);

        btn_desenvolFim.setBackground(new java.awt.Color(0, 0, 0));
        btn_desenvolFim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_desenvolFim.setForeground(new java.awt.Color(255, 255, 255));
        btn_desenvolFim.setText("Desenvolvedor");
        btn_desenvolFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desenvolFimActionPerformed(evt);
            }
        });
        getContentPane().add(btn_desenvolFim);
        btn_desenvolFim.setBounds(220, 570, 120, 30);

        lbl_imgFim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgfim.png"))); // NOI18N
        getContentPane().add(lbl_imgFim);
        lbl_imgFim.setBounds(0, 0, 650, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MenuFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuFimActionPerformed
        new FRM_PrincipalMenu( ).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_MenuFimActionPerformed

    private void btn_voltarFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarFimActionPerformed
        new FRM_Walle( ).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_voltarFimActionPerformed

    private void btn_sairFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairFimActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_sairFimActionPerformed

    private void btn_desenvolFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desenvolFimActionPerformed
            new FRM_Desenvol( ).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_desenvolFimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_MenuFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_MenuFim;
    private javax.swing.JButton btn_desenvolFim;
    private javax.swing.JButton btn_sairFim;
    private javax.swing.JButton btn_voltarFim;
    private javax.swing.JLabel lbl_imgFim;
    // End of variables declaration//GEN-END:variables
}
