/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno
 */
public class FRM_Desenvol extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Desenvol
     */
    public FRM_Desenvol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_MenuDesen = new javax.swing.JButton();
        btn_sairDesen = new javax.swing.JButton();
        lbl_imgDesen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Desenvolvedor");
        setMinimumSize(new java.awt.Dimension(650, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        btn_MenuDesen.setBackground(new java.awt.Color(0, 0, 0));
        btn_MenuDesen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_MenuDesen.setForeground(new java.awt.Color(255, 255, 255));
        btn_MenuDesen.setText("Menu Principal");
        btn_MenuDesen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuDesenActionPerformed(evt);
            }
        });
        getContentPane().add(btn_MenuDesen);
        btn_MenuDesen.setBounds(510, 540, 120, 30);

        btn_sairDesen.setBackground(new java.awt.Color(0, 0, 0));
        btn_sairDesen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sairDesen.setForeground(new java.awt.Color(255, 255, 255));
        btn_sairDesen.setText("Sair");
        btn_sairDesen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairDesenActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sairDesen);
        btn_sairDesen.setBounds(30, 540, 75, 30);

        lbl_imgDesen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgdesenv.jpg"))); // NOI18N
        getContentPane().add(lbl_imgDesen);
        lbl_imgDesen.setBounds(0, 0, 650, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MenuDesenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuDesenActionPerformed
        new FRM_PrincipalMenu( ).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_MenuDesenActionPerformed

    private void btn_sairDesenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairDesenActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_sairDesenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Desenvol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Desenvol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Desenvol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Desenvol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Desenvol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_MenuDesen;
    private javax.swing.JButton btn_sairDesen;
    private javax.swing.JLabel lbl_imgDesen;
    // End of variables declaration//GEN-END:variables
}
