
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class FRM_SilencioDosInocentes extends javax.swing.JFrame {

    /**
     * Creates new form FRM_SilencioDosInocentes
     */
    public FRM_SilencioDosInocentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_alternativasSile = new javax.swing.ButtonGroup();
        btn_avancarSile = new javax.swing.JButton();
        btn_voltarSile = new javax.swing.JButton();
        btn_desenvolSile = new javax.swing.JButton();
        btn_limparSile = new javax.swing.JButton();
        btn_sairSile = new javax.swing.JButton();
        rdb_Sile1 = new javax.swing.JRadioButton();
        rdb_Sile2 = new javax.swing.JRadioButton();
        rdb_Sile3 = new javax.swing.JRadioButton();
        rdb_Sile4 = new javax.swing.JRadioButton();
        lbl_imgSile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adivinhando O Silêncio dos Inocentes");
        setMinimumSize(new java.awt.Dimension(650, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        btn_avancarSile.setBackground(new java.awt.Color(0, 0, 0));
        btn_avancarSile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_avancarSile.setForeground(new java.awt.Color(255, 255, 255));
        btn_avancarSile.setText("Avançar");
        btn_avancarSile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_avancarSileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_avancarSile);
        btn_avancarSile.setBounds(550, 570, 77, 30);

        btn_voltarSile.setBackground(new java.awt.Color(0, 0, 0));
        btn_voltarSile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_voltarSile.setForeground(new java.awt.Color(255, 255, 255));
        btn_voltarSile.setText("Voltar");
        btn_voltarSile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarSileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltarSile);
        btn_voltarSile.setBounds(20, 570, 70, 30);

        btn_desenvolSile.setBackground(new java.awt.Color(0, 0, 0));
        btn_desenvolSile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_desenvolSile.setForeground(new java.awt.Color(255, 255, 255));
        btn_desenvolSile.setText("Desenvolvedor");
        btn_desenvolSile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desenvolSileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_desenvolSile);
        btn_desenvolSile.setBounds(220, 570, 120, 30);

        btn_limparSile.setBackground(new java.awt.Color(0, 0, 0));
        btn_limparSile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_limparSile.setForeground(new java.awt.Color(255, 255, 255));
        btn_limparSile.setText("Limpar");
        btn_limparSile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparSileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limparSile);
        btn_limparSile.setBounds(20, 380, 75, 30);

        btn_sairSile.setBackground(new java.awt.Color(0, 0, 0));
        btn_sairSile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sairSile.setForeground(new java.awt.Color(255, 255, 255));
        btn_sairSile.setText("Sair");
        btn_sairSile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairSileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sairSile);
        btn_sairSile.setBounds(120, 570, 75, 30);

        grp_alternativasSile.add(rdb_Sile1);
        rdb_Sile1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Sile1.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Sile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Sile1ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Sile1);
        rdb_Sile1.setBounds(20, 180, 330, 40);

        grp_alternativasSile.add(rdb_Sile2);
        rdb_Sile2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Sile2.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Sile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Sile2ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Sile2);
        rdb_Sile2.setBounds(20, 230, 320, 40);

        grp_alternativasSile.add(rdb_Sile3);
        rdb_Sile3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Sile3.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Sile3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Sile3ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Sile3);
        rdb_Sile3.setBounds(20, 280, 230, 40);

        grp_alternativasSile.add(rdb_Sile4);
        rdb_Sile4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Sile4.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Sile4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Sile4ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Sile4);
        rdb_Sile4.setBounds(20, 330, 310, 40);

        lbl_imgSile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgsilen.png"))); // NOI18N
        getContentPane().add(lbl_imgSile);
        lbl_imgSile.setBounds(0, 0, 650, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_avancarSileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_avancarSileActionPerformed
        new FRM_Walle( ).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_avancarSileActionPerformed

    private void btn_desenvolSileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desenvolSileActionPerformed
                new FRM_Desenvol( ).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_desenvolSileActionPerformed

    private void btn_voltarSileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarSileActionPerformed
        new FRM_Interestelar( ).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_voltarSileActionPerformed

    private void btn_sairSileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairSileActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_sairSileActionPerformed

    private void btn_limparSileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparSileActionPerformed
        grp_alternativasSile.clearSelection();
    }//GEN-LAST:event_btn_limparSileActionPerformed

    private void rdb_Sile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Sile1ActionPerformed
        JOptionPane.showMessageDialog(null,"Parabéns, você acertou!\n\nNo filme ''O Silêncio dos Inocentes'', Hannibal\nLecter é o psiquiatra, psicopata e canibal, que\nauxilia a investigação criminal.","Alternativa Correta!",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rdb_Sile1ActionPerformed

    private void rdb_Sile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Sile2ActionPerformed
            if (rdb_Sile2.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\nNo filme ''O Silêncio dos Inocentes'', Clarice Starling é uma Agende do FBI.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Sile2.setSelected(false);}
    }//GEN-LAST:event_rdb_Sile2ActionPerformed

    private void rdb_Sile3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Sile3ActionPerformed
        if (rdb_Sile3.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\nNo filme ''O Silêncio dos Inocentes'', Buffalo Bill é o procurado\nserial killer que esfola suas vítimas femininas.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Sile3.setSelected(false);}
    }//GEN-LAST:event_rdb_Sile3ActionPerformed

    private void rdb_Sile4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Sile4ActionPerformed
            if (rdb_Sile4.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\nNo filme ''O Silêncio dos Inocentes'', Jack Crawford é o\nsupervisor da Agente Starling do FBI.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Sile4.setSelected(false);}
    }//GEN-LAST:event_rdb_Sile4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_SilencioDosInocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_SilencioDosInocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_SilencioDosInocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_SilencioDosInocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_SilencioDosInocentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_avancarSile;
    private javax.swing.JButton btn_desenvolSile;
    private javax.swing.JButton btn_limparSile;
    private javax.swing.JButton btn_sairSile;
    private javax.swing.JButton btn_voltarSile;
    private javax.swing.ButtonGroup grp_alternativasSile;
    private javax.swing.JLabel lbl_imgSile;
    private javax.swing.JRadioButton rdb_Sile1;
    private javax.swing.JRadioButton rdb_Sile2;
    private javax.swing.JRadioButton rdb_Sile3;
    private javax.swing.JRadioButton rdb_Sile4;
    // End of variables declaration//GEN-END:variables
}
