
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class FRM_Interestelar extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Interestelar
     */
    public FRM_Interestelar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_alternativasInter = new javax.swing.ButtonGroup();
        btn_avancarInter = new javax.swing.JButton();
        btn_desenvolInter = new javax.swing.JButton();
        btn_voltarInter = new javax.swing.JButton();
        btn_sairInter = new javax.swing.JButton();
        btn_limparInter = new javax.swing.JButton();
        rdb_Inter1 = new javax.swing.JRadioButton();
        rdb_Inter2 = new javax.swing.JRadioButton();
        rdb_Inter3 = new javax.swing.JRadioButton();
        rdb_Inter4 = new javax.swing.JRadioButton();
        lbl_imgInter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adivinhando Interestelar");
        setMinimumSize(new java.awt.Dimension(650, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        btn_avancarInter.setBackground(new java.awt.Color(0, 0, 0));
        btn_avancarInter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_avancarInter.setForeground(new java.awt.Color(255, 255, 255));
        btn_avancarInter.setText("Avançar");
        btn_avancarInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_avancarInterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_avancarInter);
        btn_avancarInter.setBounds(550, 570, 77, 30);

        btn_desenvolInter.setBackground(new java.awt.Color(0, 0, 0));
        btn_desenvolInter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_desenvolInter.setForeground(new java.awt.Color(255, 255, 255));
        btn_desenvolInter.setText("Desenvolvedor");
        btn_desenvolInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desenvolInterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_desenvolInter);
        btn_desenvolInter.setBounds(220, 570, 120, 30);

        btn_voltarInter.setBackground(new java.awt.Color(0, 0, 0));
        btn_voltarInter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_voltarInter.setForeground(new java.awt.Color(255, 255, 255));
        btn_voltarInter.setText("Voltar");
        btn_voltarInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarInterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltarInter);
        btn_voltarInter.setBounds(20, 570, 70, 30);

        btn_sairInter.setBackground(new java.awt.Color(0, 0, 0));
        btn_sairInter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sairInter.setForeground(new java.awt.Color(255, 255, 255));
        btn_sairInter.setText("Sair");
        btn_sairInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairInterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sairInter);
        btn_sairInter.setBounds(120, 570, 75, 30);

        btn_limparInter.setBackground(new java.awt.Color(0, 0, 0));
        btn_limparInter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_limparInter.setForeground(new java.awt.Color(255, 255, 255));
        btn_limparInter.setText("Limpar");
        btn_limparInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparInterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limparInter);
        btn_limparInter.setBounds(20, 380, 75, 30);

        grp_alternativasInter.add(rdb_Inter1);
        rdb_Inter1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Inter1.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Inter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Inter1ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Inter1);
        rdb_Inter1.setBounds(10, 140, 470, 40);

        grp_alternativasInter.add(rdb_Inter2);
        rdb_Inter2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Inter2.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Inter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Inter2ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Inter2);
        rdb_Inter2.setBounds(10, 190, 150, 40);

        grp_alternativasInter.add(rdb_Inter3);
        rdb_Inter3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Inter3.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Inter3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Inter3ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Inter3);
        rdb_Inter3.setBounds(10, 240, 340, 40);

        grp_alternativasInter.add(rdb_Inter4);
        rdb_Inter4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Inter4.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Inter4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Inter4ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Inter4);
        rdb_Inter4.setBounds(10, 290, 290, 40);

        lbl_imgInter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imginter.png"))); // NOI18N
        getContentPane().add(lbl_imgInter);
        lbl_imgInter.setBounds(0, 0, 650, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_avancarInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_avancarInterActionPerformed
        new FRM_SilencioDosInocentes( ).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_avancarInterActionPerformed

    private void btn_desenvolInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desenvolInterActionPerformed
            new FRM_Desenvol( ).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_desenvolInterActionPerformed

    private void btn_voltarInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarInterActionPerformed
        new FRM_BastardosInglorios( ).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_voltarInterActionPerformed

    private void btn_sairInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairInterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_sairInterActionPerformed

    private void btn_limparInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparInterActionPerformed
        grp_alternativasInter.clearSelection();
    }//GEN-LAST:event_btn_limparInterActionPerformed

    private void rdb_Inter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Inter1ActionPerformed
        if (rdb_Inter1.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\nNo filme ''Interestelar'', a própria humanidade\ndestrói o planeta Terra.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Inter1.setSelected(false);}
    }//GEN-LAST:event_rdb_Inter1ActionPerformed

    private void rdb_Inter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Inter2ActionPerformed
            if (rdb_Inter2.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\nNo filme ''Interestelar'', Doyle era um geógrafo e astronauta que\nparticipava da missão de exploração espacial Endurance\natravés do buraco de minhoca.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Inter2.setSelected(false);}
    }//GEN-LAST:event_rdb_Inter2ActionPerformed

    private void rdb_Inter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Inter3ActionPerformed
        JOptionPane.showMessageDialog(null,"Parabéns, você acertou!\n\nNo filme ''Interestelar'' quem realmente salva a humanidade\nao encontrar outro planeta habitável é Murphy Cooper.","Alternativa Correta!",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rdb_Inter3ActionPerformed

    private void rdb_Inter4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Inter4ActionPerformed
        if (rdb_Inter4.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\nNo filme ''Interestelar'' Amélia Brand é a cientista-chefe/bióloga da expedição que está\nsendo enviada através do buraco de minhoca tentando realocar a raça humana.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Inter4.setSelected(false);}
    }//GEN-LAST:event_rdb_Inter4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Interestelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Interestelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Interestelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Interestelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Interestelar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_avancarInter;
    private javax.swing.JButton btn_desenvolInter;
    private javax.swing.JButton btn_limparInter;
    private javax.swing.JButton btn_sairInter;
    private javax.swing.JButton btn_voltarInter;
    private javax.swing.ButtonGroup grp_alternativasInter;
    private javax.swing.JLabel lbl_imgInter;
    private javax.swing.JRadioButton rdb_Inter1;
    private javax.swing.JRadioButton rdb_Inter2;
    private javax.swing.JRadioButton rdb_Inter3;
    private javax.swing.JRadioButton rdb_Inter4;
    // End of variables declaration//GEN-END:variables
}
