

import javax.swing.JOptionPane;

public class FRM_ClubeDaLuta extends javax.swing.JFrame {

    /**
     * Creates new form FRM_ClubeDaLuta
     */
    public FRM_ClubeDaLuta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_alternativasClube = new javax.swing.ButtonGroup();
        btn_avancarClube = new javax.swing.JButton();
        btn_desenvolClube = new javax.swing.JButton();
        btn_voltarClube = new javax.swing.JButton();
        btn_sairClube = new javax.swing.JButton();
        btn_limparClube = new javax.swing.JButton();
        rdb_Clube1 = new javax.swing.JRadioButton();
        rdb_Clube2 = new javax.swing.JRadioButton();
        rdb_Clube3 = new javax.swing.JRadioButton();
        rdb_Clube4 = new javax.swing.JRadioButton();
        lbl_imgClube = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adivinhando Clube da Luta");
        setMinimumSize(new java.awt.Dimension(650, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        btn_avancarClube.setBackground(new java.awt.Color(0, 0, 0));
        btn_avancarClube.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_avancarClube.setForeground(new java.awt.Color(255, 255, 255));
        btn_avancarClube.setText("Avançar");
        btn_avancarClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_avancarClubeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_avancarClube);
        btn_avancarClube.setBounds(550, 570, 77, 30);

        btn_desenvolClube.setBackground(new java.awt.Color(0, 0, 0));
        btn_desenvolClube.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_desenvolClube.setForeground(new java.awt.Color(255, 255, 255));
        btn_desenvolClube.setText("Desenvolvedor");
        btn_desenvolClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desenvolClubeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_desenvolClube);
        btn_desenvolClube.setBounds(220, 570, 120, 30);

        btn_voltarClube.setBackground(new java.awt.Color(0, 0, 0));
        btn_voltarClube.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_voltarClube.setForeground(new java.awt.Color(255, 255, 255));
        btn_voltarClube.setText("Voltar");
        btn_voltarClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarClubeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltarClube);
        btn_voltarClube.setBounds(20, 570, 70, 30);

        btn_sairClube.setBackground(new java.awt.Color(0, 0, 0));
        btn_sairClube.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sairClube.setForeground(new java.awt.Color(255, 255, 255));
        btn_sairClube.setText("Sair");
        btn_sairClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairClubeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sairClube);
        btn_sairClube.setBounds(120, 570, 75, 30);

        btn_limparClube.setBackground(new java.awt.Color(0, 0, 0));
        btn_limparClube.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_limparClube.setForeground(new java.awt.Color(255, 255, 255));
        btn_limparClube.setText("Limpar");
        btn_limparClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparClubeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limparClube);
        btn_limparClube.setBounds(20, 380, 75, 30);

        grp_alternativasClube.add(rdb_Clube1);
        rdb_Clube1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Clube1.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Clube1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Clube1ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Clube1);
        rdb_Clube1.setBounds(20, 160, 420, 40);

        grp_alternativasClube.add(rdb_Clube2);
        rdb_Clube2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Clube2.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Clube2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Clube2ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Clube2);
        rdb_Clube2.setBounds(20, 210, 420, 40);

        grp_alternativasClube.add(rdb_Clube3);
        rdb_Clube3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Clube3.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Clube3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Clube3ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Clube3);
        rdb_Clube3.setBounds(20, 260, 290, 40);

        grp_alternativasClube.add(rdb_Clube4);
        rdb_Clube4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Clube4.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Clube4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Clube4ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Clube4);
        rdb_Clube4.setBounds(20, 310, 370, 40);

        lbl_imgClube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgclubedaluta.png.jpg"))); // NOI18N
        getContentPane().add(lbl_imgClube);
        lbl_imgClube.setBounds(0, 0, 650, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdb_Clube1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Clube1ActionPerformed
        if (rdb_Clube1.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\n''Sem camisas, sem sapatos'' é a sexta regra do Clube da Luta.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Clube1.setSelected(false);}
    }//GEN-LAST:event_rdb_Clube1ActionPerformed

    private void rdb_Clube4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Clube4ActionPerformed
        if (rdb_Clube4.isSelected()){
                JOptionPane.showMessageDialog(null,"Resposta errada!\n''Dois lutadores por luta'' é a quarta regra do Clube da Luta.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
                rdb_Clube4.setSelected(false);}
    }//GEN-LAST:event_rdb_Clube4ActionPerformed

    private void btn_desenvolClubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desenvolClubeActionPerformed
            new FRM_Desenvol( ).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_desenvolClubeActionPerformed

    private void btn_voltarClubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarClubeActionPerformed
        new FRM_AliceMaravilha( ).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_voltarClubeActionPerformed

    private void btn_sairClubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairClubeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_sairClubeActionPerformed

    private void btn_limparClubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparClubeActionPerformed
        grp_alternativasClube.clearSelection();
    }//GEN-LAST:event_btn_limparClubeActionPerformed

    private void btn_avancarClubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_avancarClubeActionPerformed
        new FRM_Fragmentado( ).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_avancarClubeActionPerformed

    private void rdb_Clube2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Clube2ActionPerformed
JOptionPane.showMessageDialog(null,"Parabéns, você acertou!\n\nA primeira regra do Clube da Luta é:\n''Não fale sobre o Clube da Luta''. ","Alternativa Correta!",JOptionPane.INFORMATION_MESSAGE);        
    }//GEN-LAST:event_rdb_Clube2ActionPerformed

    private void rdb_Clube3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Clube3ActionPerformed
        if (rdb_Clube3.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\n''Uma luta por vez'' é a quinta regra do Clube da Luta.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Clube3.setSelected(false);}
    }//GEN-LAST:event_rdb_Clube3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_ClubeDaLuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_ClubeDaLuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_ClubeDaLuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_ClubeDaLuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_ClubeDaLuta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_avancarClube;
    private javax.swing.JButton btn_desenvolClube;
    private javax.swing.JButton btn_limparClube;
    private javax.swing.JButton btn_sairClube;
    private javax.swing.JButton btn_voltarClube;
    private javax.swing.ButtonGroup grp_alternativasClube;
    private javax.swing.JLabel lbl_imgClube;
    private javax.swing.JRadioButton rdb_Clube1;
    private javax.swing.JRadioButton rdb_Clube2;
    private javax.swing.JRadioButton rdb_Clube3;
    private javax.swing.JRadioButton rdb_Clube4;
    // End of variables declaration//GEN-END:variables
}
