
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author chicl
 */
public class ifrm_bastardos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrm_bastardos
     */
    public ifrm_bastardos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_alternativasBast = new javax.swing.ButtonGroup();
        btn_voltarBast = new javax.swing.JButton();
        btn_limparBast = new javax.swing.JButton();
        rdb_Bast1 = new javax.swing.JRadioButton();
        rdb_Bast2 = new javax.swing.JRadioButton();
        rdb_Bast3 = new javax.swing.JRadioButton();
        rdb_Bast4 = new javax.swing.JRadioButton();
        lbl_imgBast = new javax.swing.JLabel();

        setTitle("Bastardos Inglórios");
        setMaximumSize(new java.awt.Dimension(662, 686));
        setMinimumSize(new java.awt.Dimension(662, 686));
        setPreferredSize(new java.awt.Dimension(662, 686));
        getContentPane().setLayout(null);

        btn_voltarBast.setBackground(new java.awt.Color(0, 0, 0));
        btn_voltarBast.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_voltarBast.setForeground(new java.awt.Color(255, 255, 255));
        btn_voltarBast.setText("Fechar");
        btn_voltarBast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarBastActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltarBast);
        btn_voltarBast.setBounds(20, 570, 70, 30);

        btn_limparBast.setBackground(new java.awt.Color(0, 0, 0));
        btn_limparBast.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_limparBast.setForeground(new java.awt.Color(255, 255, 255));
        btn_limparBast.setText("Limpar");
        btn_limparBast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparBastActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limparBast);
        btn_limparBast.setBounds(20, 380, 75, 30);

        grp_alternativasBast.add(rdb_Bast1);
        rdb_Bast1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Bast1.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Bast1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Bast1ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Bast1);
        rdb_Bast1.setBounds(10, 150, 310, 40);

        grp_alternativasBast.add(rdb_Bast2);
        rdb_Bast2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Bast2.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Bast2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Bast2ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Bast2);
        rdb_Bast2.setBounds(10, 200, 230, 40);

        grp_alternativasBast.add(rdb_Bast3);
        rdb_Bast3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Bast3.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Bast3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Bast3ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Bast3);
        rdb_Bast3.setBounds(10, 250, 320, 40);

        grp_alternativasBast.add(rdb_Bast4);
        rdb_Bast4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Bast4.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Bast4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Bast4ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Bast4);
        rdb_Bast4.setBounds(10, 300, 370, 40);

        lbl_imgBast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgbast.png"))); // NOI18N
        getContentPane().add(lbl_imgBast);
        lbl_imgBast.setBounds(0, 0, 650, 650);

        setBounds(40, 23, 662, 686);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarBastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarBastActionPerformed

        dispose();
    }//GEN-LAST:event_btn_voltarBastActionPerformed

    private void btn_limparBastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparBastActionPerformed
        grp_alternativasBast.clearSelection();
    }//GEN-LAST:event_btn_limparBastActionPerformed

    private void rdb_Bast1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Bast1ActionPerformed
        if (rdb_Bast1.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\n O filme ''Bastardos Inglórios'' não se passa\ndurante a Primeira Guerra Mundial.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Bast1.setSelected(false);}
    }//GEN-LAST:event_rdb_Bast1ActionPerformed

    private void rdb_Bast2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Bast2ActionPerformed
        if (rdb_Bast2.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\n O filme ''Bastardos Inglórios'' não se\npassa durante a Guerra Fria.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Bast2.setSelected(false);}
    }//GEN-LAST:event_rdb_Bast2ActionPerformed

    private void rdb_Bast3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Bast3ActionPerformed
        JOptionPane.showMessageDialog(null,"Parabéns, você acertou!\n\nO filme ''Bastardos Inglórios'' se passa durante a Segunda\nGuerra Mundial, onde há o combate contra os nazistas.","Alternativa Correta!",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rdb_Bast3ActionPerformed

    private void rdb_Bast4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Bast4ActionPerformed
        if (rdb_Bast4.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\n O filme ''Bastardos Inglórios'' não se\npassa durante a Grande Depressão.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Bast4.setSelected(false);}
    }//GEN-LAST:event_rdb_Bast4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_limparBast;
    private javax.swing.JButton btn_voltarBast;
    private javax.swing.ButtonGroup grp_alternativasBast;
    private javax.swing.JLabel lbl_imgBast;
    private javax.swing.JRadioButton rdb_Bast1;
    private javax.swing.JRadioButton rdb_Bast2;
    private javax.swing.JRadioButton rdb_Bast3;
    private javax.swing.JRadioButton rdb_Bast4;
    // End of variables declaration//GEN-END:variables
}
