
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author chicl
 */
public class ifrm_clubedaluta extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrm_clubedaluta
     */
    public ifrm_clubedaluta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_alternativasClube = new javax.swing.ButtonGroup();
        btn_voltarClube = new javax.swing.JButton();
        btn_limparClube = new javax.swing.JButton();
        rdb_Clube1 = new javax.swing.JRadioButton();
        rdb_Clube2 = new javax.swing.JRadioButton();
        rdb_Clube3 = new javax.swing.JRadioButton();
        rdb_Clube4 = new javax.swing.JRadioButton();
        lbl_imgClube = new javax.swing.JLabel();

        setTitle("Clube da Luta");
        setMaximumSize(new java.awt.Dimension(662, 686));
        setMinimumSize(new java.awt.Dimension(662, 686));
        setPreferredSize(new java.awt.Dimension(662, 686));
        getContentPane().setLayout(null);

        btn_voltarClube.setBackground(new java.awt.Color(0, 0, 0));
        btn_voltarClube.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_voltarClube.setForeground(new java.awt.Color(255, 255, 255));
        btn_voltarClube.setText("Fechar");
        btn_voltarClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarClubeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltarClube);
        btn_voltarClube.setBounds(20, 570, 70, 30);

        btn_limparClube.setBackground(new java.awt.Color(0, 0, 0));
        btn_limparClube.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_limparClube.setForeground(new java.awt.Color(255, 255, 255));
        btn_limparClube.setText("Limpar");
        btn_limparClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparClubeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limparClube);
        btn_limparClube.setBounds(20, 380, 75, 30);

        grp_alternativasClube.add(rdb_Clube1);
        rdb_Clube1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Clube1.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Clube1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Clube1ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Clube1);
        rdb_Clube1.setBounds(20, 160, 420, 40);

        grp_alternativasClube.add(rdb_Clube2);
        rdb_Clube2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Clube2.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Clube2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Clube2ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Clube2);
        rdb_Clube2.setBounds(20, 210, 420, 40);

        grp_alternativasClube.add(rdb_Clube3);
        rdb_Clube3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Clube3.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Clube3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Clube3ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Clube3);
        rdb_Clube3.setBounds(20, 260, 290, 40);

        grp_alternativasClube.add(rdb_Clube4);
        rdb_Clube4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Clube4.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Clube4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Clube4ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Clube4);
        rdb_Clube4.setBounds(20, 310, 370, 40);

        lbl_imgClube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgclubedaluta.png.jpg"))); // NOI18N
        getContentPane().add(lbl_imgClube);
        lbl_imgClube.setBounds(0, 0, 650, 650);

        setBounds(40, 23, 662, 686);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarClubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarClubeActionPerformed
       
        dispose();
    }//GEN-LAST:event_btn_voltarClubeActionPerformed

    private void btn_limparClubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparClubeActionPerformed
        grp_alternativasClube.clearSelection();
    }//GEN-LAST:event_btn_limparClubeActionPerformed

    private void rdb_Clube1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Clube1ActionPerformed
        if (rdb_Clube1.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\n''Sem camisas, sem sapatos'' é a sexta regra do Clube da Luta.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Clube1.setSelected(false);}
    }//GEN-LAST:event_rdb_Clube1ActionPerformed

    private void rdb_Clube2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Clube2ActionPerformed
        JOptionPane.showMessageDialog(null,"Parabéns, você acertou!\n\nA primeira regra do Clube da Luta é:\n''Não fale sobre o Clube da Luta''. ","Alternativa Correta!",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rdb_Clube2ActionPerformed

    private void rdb_Clube3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Clube3ActionPerformed
        if (rdb_Clube3.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\n''Uma luta por vez'' é a quinta regra do Clube da Luta.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Clube3.setSelected(false);}
    }//GEN-LAST:event_rdb_Clube3ActionPerformed

    private void rdb_Clube4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Clube4ActionPerformed
        if (rdb_Clube4.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\n''Dois lutadores por luta'' é a quarta regra do Clube da Luta.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Clube4.setSelected(false);}
    }//GEN-LAST:event_rdb_Clube4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_limparClube;
    private javax.swing.JButton btn_voltarClube;
    private javax.swing.ButtonGroup grp_alternativasClube;
    private javax.swing.JLabel lbl_imgClube;
    private javax.swing.JRadioButton rdb_Clube1;
    private javax.swing.JRadioButton rdb_Clube2;
    private javax.swing.JRadioButton rdb_Clube3;
    private javax.swing.JRadioButton rdb_Clube4;
    // End of variables declaration//GEN-END:variables
}
