
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author chicl
 */
public class ifrm_walle extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrm_walle
     */
    public ifrm_walle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_alternativasWall = new javax.swing.ButtonGroup();
        btn_voltarWall = new javax.swing.JButton();
        btn_limparWall = new javax.swing.JButton();
        rdb_Wall1 = new javax.swing.JRadioButton();
        rdb_Wall2 = new javax.swing.JRadioButton();
        rdb_Wall3 = new javax.swing.JRadioButton();
        rdb_Wall4 = new javax.swing.JRadioButton();
        lbl_imgWall = new javax.swing.JLabel();

        setTitle("Wall-E");
        setMaximumSize(new java.awt.Dimension(662, 686));
        setMinimumSize(new java.awt.Dimension(662, 686));
        getContentPane().setLayout(null);

        btn_voltarWall.setBackground(new java.awt.Color(0, 0, 0));
        btn_voltarWall.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_voltarWall.setForeground(new java.awt.Color(255, 255, 255));
        btn_voltarWall.setText("Fechar");
        btn_voltarWall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarWallActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltarWall);
        btn_voltarWall.setBounds(20, 570, 70, 30);

        btn_limparWall.setBackground(new java.awt.Color(0, 0, 0));
        btn_limparWall.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_limparWall.setForeground(new java.awt.Color(255, 255, 255));
        btn_limparWall.setText("Limpar");
        btn_limparWall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparWallActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limparWall);
        btn_limparWall.setBounds(20, 410, 75, 30);

        grp_alternativasWall.add(rdb_Wall1);
        rdb_Wall1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Wall1.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Wall1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Wall1ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Wall1);
        rdb_Wall1.setBounds(20, 210, 140, 40);

        grp_alternativasWall.add(rdb_Wall2);
        rdb_Wall2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Wall2.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Wall2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Wall2ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Wall2);
        rdb_Wall2.setBounds(20, 260, 170, 40);

        grp_alternativasWall.add(rdb_Wall3);
        rdb_Wall3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Wall3.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Wall3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Wall3ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Wall3);
        rdb_Wall3.setBounds(20, 310, 160, 40);

        grp_alternativasWall.add(rdb_Wall4);
        rdb_Wall4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Wall4.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Wall4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Wall4ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Wall4);
        rdb_Wall4.setBounds(20, 360, 110, 40);

        lbl_imgWall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgwall.png"))); // NOI18N
        getContentPane().add(lbl_imgWall);
        lbl_imgWall.setBounds(0, 0, 650, 650);

        setBounds(40, 23, 662, 686);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarWallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarWallActionPerformed

        dispose();
    }//GEN-LAST:event_btn_voltarWallActionPerformed

    private void btn_limparWallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparWallActionPerformed
        grp_alternativasWall.clearSelection();
    }//GEN-LAST:event_btn_limparWallActionPerformed

    private void rdb_Wall1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Wall1ActionPerformed
        if (rdb_Wall1.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\nO robô ''R2-D2'' pertence a saga ''Star Wars'',\nportanto não está presente no filme citado.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Wall1.setSelected(false);}
    }//GEN-LAST:event_rdb_Wall1ActionPerformed

    private void rdb_Wall2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Wall2ActionPerformed
        if (rdb_Wall2.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\nO robô ''BURN-E'' ,que significa ''Basic Utility\nRepair Nano Engineer'', é um robô soldador.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Wall2.setSelected(false);}
    }//GEN-LAST:event_rdb_Wall2ActionPerformed

    private void rdb_Wall3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Wall3ActionPerformed
        if (rdb_Wall3.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\nO robô ''C-3PO'' pertence a saga ''Star Wars'',\nportanto não está presente no filme citado.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Wall3.setSelected(false);}
    }//GEN-LAST:event_rdb_Wall3ActionPerformed

    private void rdb_Wall4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Wall4ActionPerformed
        JOptionPane.showMessageDialog(null,"Parabéns, você acertou!\n\n O robô ''EVA'' é o moderno robô\npor quem ''WALL-E'' se apaixona.","Alternativa Correta!",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rdb_Wall4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_limparWall;
    private javax.swing.JButton btn_voltarWall;
    private javax.swing.ButtonGroup grp_alternativasWall;
    private javax.swing.JLabel lbl_imgWall;
    private javax.swing.JRadioButton rdb_Wall1;
    private javax.swing.JRadioButton rdb_Wall2;
    private javax.swing.JRadioButton rdb_Wall3;
    private javax.swing.JRadioButton rdb_Wall4;
    // End of variables declaration//GEN-END:variables
}
