/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author chicl
 */
public class ifrm_agradecimento extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrm_agradecimento
     */
    public ifrm_agradecimento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_voltarInter = new javax.swing.JButton();
        lbl_imgFim = new javax.swing.JLabel();

        setTitle("Agradecimento");
        setMaximumSize(new java.awt.Dimension(662, 686));
        setMinimumSize(new java.awt.Dimension(662, 686));
        getContentPane().setLayout(null);

        btn_voltarInter.setBackground(new java.awt.Color(0, 0, 0));
        btn_voltarInter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_voltarInter.setForeground(new java.awt.Color(255, 255, 255));
        btn_voltarInter.setText("Fechar");
        btn_voltarInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarInterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltarInter);
        btn_voltarInter.setBounds(20, 570, 70, 30);

        lbl_imgFim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundo2.jpg"))); // NOI18N
        getContentPane().add(lbl_imgFim);
        lbl_imgFim.setBounds(0, 0, 650, 650);

        setBounds(40, 23, 662, 686);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarInterActionPerformed

        dispose();
    }//GEN-LAST:event_btn_voltarInterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_voltarInter;
    private javax.swing.JLabel lbl_imgFim;
    // End of variables declaration//GEN-END:variables
}
