
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author chicl
 */
public class ifrm_silenciodosinocentes extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrm_silenciodosinocentes
     */
    public ifrm_silenciodosinocentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_alternativasSile = new javax.swing.ButtonGroup();
        btn_voltarSile = new javax.swing.JButton();
        btn_limparSile = new javax.swing.JButton();
        rdb_Sile1 = new javax.swing.JRadioButton();
        rdb_Sile2 = new javax.swing.JRadioButton();
        rdb_Sile3 = new javax.swing.JRadioButton();
        rdb_Sile4 = new javax.swing.JRadioButton();
        lbl_imgSile = new javax.swing.JLabel();

        setTitle("O Silêncio dos Inocentes");
        setMaximumSize(new java.awt.Dimension(662, 686));
        setMinimumSize(new java.awt.Dimension(662, 686));
        getContentPane().setLayout(null);

        btn_voltarSile.setBackground(new java.awt.Color(0, 0, 0));
        btn_voltarSile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_voltarSile.setForeground(new java.awt.Color(255, 255, 255));
        btn_voltarSile.setText("Fechar");
        btn_voltarSile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarSileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltarSile);
        btn_voltarSile.setBounds(20, 570, 70, 30);

        btn_limparSile.setBackground(new java.awt.Color(0, 0, 0));
        btn_limparSile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_limparSile.setForeground(new java.awt.Color(255, 255, 255));
        btn_limparSile.setText("Limpar");
        btn_limparSile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparSileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limparSile);
        btn_limparSile.setBounds(20, 380, 75, 30);

        grp_alternativasSile.add(rdb_Sile1);
        rdb_Sile1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Sile1.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Sile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Sile1ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Sile1);
        rdb_Sile1.setBounds(20, 180, 330, 40);

        grp_alternativasSile.add(rdb_Sile2);
        rdb_Sile2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Sile2.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Sile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Sile2ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Sile2);
        rdb_Sile2.setBounds(20, 230, 320, 40);

        grp_alternativasSile.add(rdb_Sile3);
        rdb_Sile3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Sile3.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Sile3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Sile3ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Sile3);
        rdb_Sile3.setBounds(20, 280, 230, 40);

        grp_alternativasSile.add(rdb_Sile4);
        rdb_Sile4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        rdb_Sile4.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Sile4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_Sile4ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_Sile4);
        rdb_Sile4.setBounds(20, 330, 310, 40);

        lbl_imgSile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgsilen.png"))); // NOI18N
        getContentPane().add(lbl_imgSile);
        lbl_imgSile.setBounds(0, 0, 650, 650);

        setBounds(40, 23, 662, 686);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarSileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarSileActionPerformed

        dispose();
    }//GEN-LAST:event_btn_voltarSileActionPerformed

    private void btn_limparSileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparSileActionPerformed
        grp_alternativasSile.clearSelection();
    }//GEN-LAST:event_btn_limparSileActionPerformed

    private void rdb_Sile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Sile1ActionPerformed
        JOptionPane.showMessageDialog(null,"Parabéns, você acertou!\n\nNo filme ''O Silêncio dos Inocentes'', Hannibal\nLecter é o psiquiatra, psicopata e canibal, que\nauxilia a investigação criminal.","Alternativa Correta!",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rdb_Sile1ActionPerformed

    private void rdb_Sile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Sile2ActionPerformed
        if (rdb_Sile2.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\nNo filme ''O Silêncio dos Inocentes'', Clarice Starling é uma Agende do FBI.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Sile2.setSelected(false);}
    }//GEN-LAST:event_rdb_Sile2ActionPerformed

    private void rdb_Sile3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Sile3ActionPerformed
        if (rdb_Sile3.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\nNo filme ''O Silêncio dos Inocentes'', Buffalo Bill é o procurado\nserial killer que esfola suas vítimas femininas.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Sile3.setSelected(false);}
    }//GEN-LAST:event_rdb_Sile3ActionPerformed

    private void rdb_Sile4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_Sile4ActionPerformed
        if (rdb_Sile4.isSelected()){
            JOptionPane.showMessageDialog(null,"Resposta errada!\nNo filme ''O Silêncio dos Inocentes'', Jack Crawford é o\nsupervisor da Agente Starling do FBI.","Alternativa Errada!",JOptionPane.ERROR_MESSAGE);
            rdb_Sile4.setSelected(false);}
    }//GEN-LAST:event_rdb_Sile4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_limparSile;
    private javax.swing.JButton btn_voltarSile;
    private javax.swing.ButtonGroup grp_alternativasSile;
    private javax.swing.JLabel lbl_imgSile;
    private javax.swing.JRadioButton rdb_Sile1;
    private javax.swing.JRadioButton rdb_Sile2;
    private javax.swing.JRadioButton rdb_Sile3;
    private javax.swing.JRadioButton rdb_Sile4;
    // End of variables declaration//GEN-END:variables
}
